export const ROUTES = {
  home: '/',
  aboutCompany: '/about-company',
  branches: '/branches',
  visionAndMessage: '/vision-and-message',
  organizationStructure: '/organization-structure',
  contractsRegulation: '/contracts-regulation',
  companyAchievements: '/company-achievements',
  adviceAndContact: '/advice-and-contact',
  forKidsAndWomen: '/for-kids-and-women',
  waterQuality: '/water-quality',
  refiningWater: '/refining-water',
  labOfCompanyWater: '/lab-of-company-water',
  sewageTreatment: '/sewage-treatment',
  safeSewageDisposal: '/safe-sewage-disposal',
  saveSewageNetwork: '/save-sewage-network',
  industrialWaste: '/industrial-waste',
  industrialWasteRole: '/industrial-waste-role',
  customerCharter: '/Customer-Charter',
  newsArchive: '/news-archive',
  newsDetails: '/news/:id',
  projectsArchive: '/projects-archive',
  projectDetails: '/projects/:id',
  tendersArchive: '/tenders-archive',
  tenderDetails: '/tenders/:id',
  generalAdminTraining: '/general-admin-training',
  callCenter: '/call-center',
  jobsAndCompetition: '/jobs-and-competition',
  resultOfWorker: '/result_of_worker',
} as const;

export const LEGACY_ROUTE_REDIRECTS: ReadonlyArray<{ from: string; to: string }> = [
  { from: '/an-elsherka', to: ROUTES.aboutCompany },
  { from: '/branch-of-company', to: ROUTES.branches },
  { from: '/contract-and-sell', to: ROUTES.contractsRegulation },
  { from: '/company-achivement', to: ROUTES.companyAchievements },
  { from: '/adviceAndContact', to: ROUTES.adviceAndContact },
  { from: '/forKidsAndWomen', to: ROUTES.forKidsAndWomen },
  { from: '/forKids', to: ROUTES.forKidsAndWomen },
  { from: '/toWomen', to: ROUTES.forKidsAndWomen },
  { from: '/Riddence-waste-water', to: ROUTES.safeSewageDisposal },
  { from: '/save-web-waste-water', to: ROUTES.saveSewageNetwork },
  { from: '/manufactring-waste', to: ROUTES.industrialWaste },
  { from: '/waste-water-in-manufactring', to: ROUTES.industrialWasteRole },
  { from: '/news-company', to: ROUTES.newsArchive },
  { from: '/projects-company', to: ROUTES.projectsArchive },
  { from: '/projects', to: ROUTES.projectsArchive },
  { from: '/allTenders', to: ROUTES.tendersArchive },
  { from: '/alltenders', to: ROUTES.tendersArchive },
] as const;
